### ISSUE TITLE
Sass external libraries (compass) dependency check error

### ISSUE THREAD

**Issue by btaens** [markstory/mini-asset#1]
Hello,
Dependency checking now works, however, if I'm trying to import an external library (compass, for example, with `@import "compass";`, **File\Local::__construct()** throws an error, saying it can't find compass.scss.

I made a CompassFIlter for this purpose, which basically extends ScssFilter and appends '--compass' at the end of the sass executable, so it's not technically a problem with the core functionality, but perhaps a feature in the filters to exclude a dependency would be useful, or maybe just throw a warning instead of an error if a dependency is not found.

**Comment by markstory** [comment]
Skipping missing files is a good option too I think.
