### ISSUE TITLE
Missing directory separator when using ROOT constant in ClosureJs.php

### ISSUE THREAD

**Issue by casdevs** [markstory/mini-asset#11]
Hi Mark,

just tried to use your new mini-asset plugin in a CakePHP 3 project to minify js assets with ClosureJs.

However, compiler.jar could not be found in vendor/closure path due to a missing DS in the `_findExecutable` call.

line 50
`$jar = $this->_findExecutable([ROOT . 'vendor'], $this->_settings['path']);`

should become
`$jar = $this->_findExecutable([ROOT . DS . 'vendor'], $this->_settings['path']);`

as `ROOT` is defined by cake without trailing slash explicitly.

I think your tests don't come up with this error because you use
`define('ROOT', dirname(__DIR__) . DS);`
in `tests/bootstrap.php` which differs from the way CakePHP defines the `ROOT`constant itself.

Best regards,
Stefan

**Comment by markstory** [comment]
0.1.1 tagged.
