### ISSUE TITLE
Global require

### ISSUE THREAD

**Issue by Swader** [markstory/mini-asset#12]
I suggest adding global installation instructions into the readme:

```
composer global require markstory:mini-asset --dev
```

and adding `__DIR__ . '../../../autoload.php'` as the first option into the bin file under autoload paths, in order to accommodate this (it crashes on global install otherwise).

Alternatively, consider using something like [box](http://www.sitepoint.com/boxing-apps-phars-quickly-easily-box/) to automate this and avoid the options array altogether.

**Comment by markstory** [comment]
Fixed and packaged into 1.0.1.
