### ISSUE TITLE
src/Filter/LessPHP.php: Change the dependency

### ISSUE THREAD

**Issue by ivantcholakov** [markstory/mini-asset#15]
Currently the filter LessPHP.php depends on the project https://github.com/leafo/lessphp. But this project is maintained too slowly, many issues stay open for long time.

Could you consider the project https://github.com/oyejorge/less.php as an alternative?

**Comment by markstory** [comment]
#14 suggests exactly that. Albeit through adding a new filter class.

**Comment by Swader** [comment]
@markstory any changes with this? It's been merged for a while but the 1.0.2 milestone hasn't been released yet. Any indication of a release soon? Currently fixable by requiring dev-master, but would be nice to have this in stable.

**Comment by markstory** [comment]
I just forgot. I will do a release tonight.
