### ISSUE TITLE
Less and SCSS filters in pure PHP

### ISSUE THREAD

**Issue by Laykou** [markstory/mini-asset#17]
Hello,

what do you think about using Less and SCSS compilers written purly in PHP?

It would make the code less dependent on installing NodeJS or Ruby.

Less: https://github.com/leafo/lessphp
Scss: https://github.com/leafo/scssphp

If you agree I can send a PR.

**Comment by Laykou** [comment]
e.g. this works:

``` PHP
use Leafo\ScssPhp\Compiler;
use MiniAsset\Filter\AssetFilter;

/**
 * Pre-processing filter that adds support for SCSS files.
 */
class ScssFilter extends AssetFilter
{

    protected $_settings = [
        'ext' => '.scss',
    ];

    /**
     * Runs SCSS compiler against any files that match the configured extension.
     *
     * @param string $filename The name of the input file.
     * @param string $input The content of the file.
     * @return string
     */
    public function input($filename, $input)
    {
        if (substr($filename, strlen($this->_settings['ext']) * -1) !== $this->_settings['ext']) {
            return $input;
        }

        $scss = new Compiler();
        return $scss->compile($input);
    }
}

```

**Comment by markstory** [comment]
There are already filters for both.

**Comment by markstory** [comment]
ScssPhp and Lessphp.

**Comment by Laykou** [comment]
Hello, sorry, I've missed this changed. Anyway Scss library https://github.com/leafo/scssphp is updated and now uses namespaces as you can see also from my example. The compiler class is `new \Leafo\ScssPhp\Compiler()` instead of former `new scssc()`.
