### ISSUE TITLE
Sass partials skipped in dependency check

### ISSUE THREAD

**Issue by btaens** [markstory/mini-asset#2]
Hey,
In sass files, if, say, you `@import "partial";`, sass looks for both a **partial.scss**, or a **_partial.scss**. Mini-asset however only checks for a **partial.scss** and doesn't look for the underscored version, and so automatically skips the dependency check.

**Comment by markstory** [comment]
I totally forgot sass included this magic :cry:

**Comment by btaens** [comment]
I think less might also do it, though I'm more of a sass guy.

**Comment by markstory** [comment]
Less doesn't magically mangle names adding prefixes.
