### ISSUE TITLE
Glob paths when resolving CSS dependencies

### ISSUE THREAD

**Issue by berarma** [markstory/mini-asset#21]
I think glob paths don't work when resolving CSS dependencies. The function that searches the file uses _file_exists_ directly on the path setting and the file name.

``` ini
[css]
paths[] = WEBROOT/css/*
[public.css]
files[] = public/base.less
```

This will check for the file "WEBROOT/css/*/public/base.less".

**Comment by markstory** [comment]
I'll take a look. Globbing should work.

**Comment by markstory** [comment]
Where are you seeing that `WEBROOT/css/*/public/base.less` is being checked by `file_exists`? I took a look at the test cases and `/*` is correctly expanded by AssetScanner for both CSS and JS files.

**Comment by berarma** [comment]
I put a debug($path) statement before line:
https://github.com/markstory/mini-asset/blob/master/src/Filter/CssDependencyTrait.php#L96

**Comment by markstory** [comment]
Ok. Which less filter are you using?

**Comment by berarma** [comment]
LessCss.

**Comment by markstory** [comment]
OK, I'll see if I can reproduce this problem on my side.

**Comment by berarma** [comment]
I've just looked at the _AssetScanner_ tests too and that's not where the problem lies. See this back trace and you'll see there's no AssetScanner involved. _AssetScanner_ correctly expands the glob paths at initialization but the _CssDependencyTrait_ code doesn't use that, it uses the raw paths instead.

```
#0  MiniAsset\Filter\LessCss->_findFile(variables.less) called at [/home/xxxxx/vendor/markstory/mini-asset/src/Filter/CssDependencyTrait.php:64]
#1  MiniAsset\Filter\LessCss->getDependencies() called at [/home/xxxxx/vendor/markstory/mini-asset/src/Output/FreshTrait.php:93]
#2  MiniAsset\Output\AssetCacher->isFresh() called at [/home/xxxxx/vendor/markstory/asset_compress/src/Routing/Filter/AssetCompressorFilter.php:65]
#3  AssetCompress\Routing\Filter\AssetCompressorFilter->beforeDispatch() called at [/home/xxxxx/vendor/cakephp/cakephp/src/Routing/DispatcherFilter.php:145]
#4  Cake\Routing\DispatcherFilter->handle() called at [/home/xxxxx/vendor/cakephp/cakephp/src/Event/EventManager.php:390]
#5  Cake\Event\EventManager->_callListener() called at [/home/xxxxx/vendor/cakephp/cakephp/src/Event/EventManager.php:356]
#6  Cake\Event\EventManager->dispatch() called at [/home/xxxxx/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php:78]
#7  Cake\Routing\Dispatcher->dispatchEvent() called at [/home/xxxxx/vendor/cakephp/cakephp/src/Routing/Dispatcher.php:62]
#8  Cake\Routing\Dispatcher->dispatch() called at [/home/xxxxx/webroot/index.php:37]
```

For my case I've solved it using a directory path without stars, but since it's a deviation from the expected behavior I guess it should be fixed or at least warn about this caveat.

**Comment by markstory** [comment]
Thanks for that tip. I'll take a look.

**Comment by markstory** [comment]
Pull request up now. Looks like this was caused by how asset targets were created. They were being created with un-expanded glob paths.
