### ISSUE TITLE
Using paths in filters doesn't work

### ISSUE THREAD

**Issue by berarma** [markstory/mini-asset#22]
I've tried to define paths for the LessCSS filter in the following lines:

``` ini
[filter_LessCss]
node = /usr/local/bin/node
node_path = /usr/local/lib/node_modules
paths[] = APP/vendor/twbs/bootstrap/less/*
paths[] = WEBROOT/css/*
```

I get this message:

> Warning (2): strtr() expects parameter 1 to be string, array given [ROOT/vendor/markstory/mini-asset/src/AssetConfig.php, line 306]

I'm guessing that's because the settings array isn't processed recursively when constant substitution takes place, thus an array is passed instead of the elements of that array. This is the line: https://github.com/markstory/mini-asset/blob/master/src/AssetConfig.php#L443

**Comment by markstory** [comment]
Why are paths being defined in the filter? Paths are usually defined at the extension level not inside a filter. I'm not even sure that defining paths inside the filter will work, as the [paths will be overwritten by the extension settings](https://github.com/markstory/mini-asset/blob/master/src/Filter/AssetFilter.php#L41-L46)

**Comment by berarma** [comment]
Oops, my fault then. I wanted to define paths specific to LESS files and I thought this should work since the LessCss filter uses this setting, but now I see the filter would use the paths defined in the extension settings instead.

I tried to do this because I have some paths that are only needed for specific filters, but declaring them globally for all filters isn't causing any problem.

**Comment by markstory** [comment]
Okey doke.
