### ISSUE TITLE
Problem with UgilfyJs command

### ISSUE THREAD

**Issue by szymach** [markstory/mini-asset#39]
Hey, in [this](https://github.com/markstory/mini-asset/blob/master/src/Filter/Uglifyjs.php#L44) line the options are always prepended with a `-`, but why? It causes errors in my build (using UglifyJs 1.3.8 and node 4.2.6), since it treats `-` as a file to uglify. Am I doing something wrong, or is this an error? Thanks in advance for the reply.

**Comment by markstory** [comment]
The `-` is used to tell uglify that we're going to be piping in the javascript code via stdin, instead of giving it filenames. You can simulate how mini-asset works on the command line using:

```bash
cat path/to/file.js | node_modules/.bin/uglifyjs - -m
```

**Comment by szymach** [comment]
Alright, but do you have any idea why it treats the dash as a filename? There is no way for me to modify the command through configuration, so currently I am stuck with just removing it in vendor code.

**Comment by markstory** [comment]
No idea. Are you on windows? You might want to try a newer version of uglify as well.

**Comment by szymach** [comment]
Hey, 
Sorry but I stopped using your tool, so I am closing this issue. Best of luck anyways and thanks for the help.
