### ISSUE TITLE
Issue with AssetConfig::_addConstants()

### ISSUE THREAD

**Issue by ajfranzoia** [markstory/mini-asset#4]
I'm having an issue with `_addConstants()` when having open_basedir restrictions in effect.
When user constants are passed to this method, it will raise a warning when treating `DS` constant as a path if the root path is not contained in open_basedir config (https://github.com/markstory/mini-asset/blob/master/src/AssetConfig.php#L121).
Maybe having some kind of constants whitelist/blacklist to check against the value before validating if path exists?

**Comment by markstory** [comment]
I think excluding DIRECTORY_SEPARATOR is simple enough. Do you often have other constants that your applications can't access because of open basedir?

**Comment by ajfranzoia** [comment]
Yeah, that looks enough, since non-path constants will be filtered out in the `strpos($value, DIRECTORY_SEPARATOR)` check.
