### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by mrothauer** [markstory/mini-asset#71]
When I change the php-requirements of my project's composer.json to 8.2 and then run `composer update` i get a downgraded version of mini-asset (which then throws errors).

`Downgrading markstory/mini-asset (1.11.0 => 1.9.1)`

Would it be possible to change <8.2 to <=8.2?

https://github.com/markstory/mini-asset/blob/5b3f7d7876d3f7bd9377664208cc386341025e5f/composer.json#L20

**Comment by markstory** [comment]
> Would it be possible to change <8.2 to <=8.2?

Probably. If CI configuration is updated, and tests pass I see no reason the compatible PHP version can't be updated.

**Comment by mrothauer** [comment]
Hi Mark,

I just tried to update to php 8.2
https://github.com/markstory/mini-asset/compare/master...mrothauer:mini-asset:master

Github Actions throws a psalm error, but I am not sure if it was caused by my changings
https://github.com/mrothauer/mini-asset/actions/runs/3850103365

```
[ParseError: vendor/laminas/laminas-diactoros/src/functions/marshal_headers_from_sapi.php#L29](https://github.com/mrothauer/mini-asset/commit/2689566dbbd0d1e3be67f909004a172273a3a34f#annotation_7713975583)
vendor/laminas/laminas-diactoros/src/functions/marshal_headers_from_sapi.php:29:18: ParseError: Syntax error, unexpected T_STRING, expecting T_PAAMAYIM_NEKUDOTAYIM on line 29 (see
```

BTW: There are a lot of deprecations due to Ubuntu 18.04, Ubuntu should be updated to 22.04

**Comment by markstory** [comment]
I've opened a pull request to add php 8.2 to the CI matrix. If you're looking for a 8.1+ only version of mini-asset the `2.x` branch drops support for PHP7 and adds more native typehints.

**Comment by mrothauer** [comment]
Thank you. As the tests for 8.2 are ok, please don't forget to change the php-requirement in composer.json (see my first comment) before merging into master.
https://github.com/markstory/mini-asset/blob/5b3f7d7876d3f7bd9377664208cc386341025e5f/composer.json#L20

> If you're looking for a 8.1+ only version of mini-asset the 2.x branch drops support for PHP7 and adds more native typehints.

I'm not using mini-asset directly, I'm using asset_compress. But as I see, I could use https://github.com/markstory/asset_compress/tree/5.x to get the 2.x branch of mini-asset.

**Comment by mrothauer** [comment]
Thank you!
#72
