### ISSUE TITLE
Add CleanCss Filter to 2.x Branch (CakePHP 5)

### ISSUE THREAD

**Issue by mrothauer** [markstory/mini-asset#75]
Hi Mark,
I updated my app to CakePHP 5 and realized, that my commits for the CleanCss filter are not yet merged to the 2.x branch. Could you do that please?

https://github.com/markstory/mini-asset/compare/2.x...master

Minor adaptions for the filter are required (argument types and return types), here you find the adapted file which is working:
https://github.com/foodcoopshop/foodcoopshop/blob/issue-917-cakephp-5-update/config/mini-asset/CleanCss.php

I can do the PR if you want as soon as you merge the commits into the branch.

Thank you,
Mario

**Comment by markstory** [comment]
Released 2.1.0
