### ISSUE TITLE
Wrapping issues

### ISSUE THREAD

**Issue by rudy1976s** [markstory/mini-asset#76]
After upgrading to cakephp 5 I have the following error:

`: file_exists(): Unable to find the wrapper &quot;wss&quot; - did you forget to enable it when you configured PHP? [in /var/www/acme/vendor/markstory/mini-asset/src/AssetConfig.php, line 129`
I tried to search on google without luck.
I have added a "@" as workardoun on line 129.
How can I solve this problem?

Thank you 

Rudy

**Comment by markstory** [comment]
Do you have a constant in your application that starts with a `wss:`?

**Comment by rudy1976s** [comment]
Hello Mark
I have a configuration in environment file like the following : 
`SOCKETS_ENDPOINT="wss://vps-green.acmecms.it/socket/"`

and some constants like the following

`
define("WEBSOCKETS_ENDPOINT", Configure::read("sockets_endpoint", "wss://' . Configure::read('application_hostname') . '/socket/"));
`
It seems that everything is correctly wrapped with ""
