### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by jorisvaesen** [markstory/mini-asset#77]
We are currently using the 1.x release (because of asset-compress 4.x) but since we upgraded to php 8.3 the mini asset version got downgraded to 1.4.2 because of this composer constraint in recent 1.x releases: `"php": ">=7.4,<8.3"`.

What is the reason to not allow php8.3 for the latest 1.x releases?

**Comment by markstory** [comment]
> What is the reason to not allow php8.3 for the latest 1.x releases?

Because I've not needed it, and no one has sent a pull request to update the CI build jobs.
