### ISSUE TITLE
theme: is unresolved in path

### ISSUE THREAD

**Issue by Graziel** [markstory/mini-asset#8]
as of commit 25f90131af3896cc3d93e17693801b33abe4b69a (or around cant be 100% sure) asset compress ignores 'themes[] =' ie it doesnt replace **theme:** in path with currently set theme 

ive trace it back to [AssetConfig.php](https://github.com/markstory/mini-asset/blob/master/src/AssetConfig.php#L579-L585) doesnt know how to select current theme

**Comment by markstory** [comment]
The key was never `themes[]=` it was `theme`. Does that also not work?

**Comment by Graziel** [comment]
whoops i should clarify that i ment 'themes[] =' in asset_compress.ini
; \* themes - Define which plugins are themes. Theme plugins will be scanned
;   for asset files when building targets containing themed files.
[General]
cacheConfig = false
alwaysEnableController = false
themes[] = ThemeDefault

i was using it fine till todays update

**Comment by markstory** [comment]
Ah ok, I'll take a look.

**Comment by markstory** [comment]
What isn't working? I tried locally and the themed file building seemed to work ok. Both the dev builder, and CLI tool were able to generate a themed file correctly. What does your target definition look like? Mine was

``` ini
[app.css]
theme = true
files[] = base.css
files[] = cake.css
files[] = theme:css/photos.css
```

**Comment by Graziel** [comment]
sorry after looking thoroughly in code ive found my old hacks to change theme to null in some views in some specific cases, i was sure its was after plugin update because it was working yesterday on index page (clearing tmp solved this one and removing old hacks solved the other pages)

sorry again for hassle
